version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./apps/backend/.env #shared env file with strapi application 
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./
    restart: always
    volumes:
      - ./apps/backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - db
    networks:
      - app

  frontend:
    build:
      context: ./
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/var/www/
      - ./apps/frontend:/usr/src/app/
      - ./apps/frontend/node_modules:/usr/src/app/node_modules
      - ./apps/frontend/.next:/usr/src/app/.next
    depends_on:
      backend:
        condition: service_completed_successfully
    networks:
      - app

networks:
  app:
    driver: bridge
