version: '3.9'
services:
  #turborepo
  turbo:
    container_name: akila-chain
    build:
      context: .
    ports:
      - "3000:3000"
      - "1337:1337"
    environment:
      - STRAPI_VERSION=4.2.3 #specify your strapi version here (need to be same as package.json)
    volumes:
      - ./:/app/
       # Just specify a path and let the Engine create a volume
      - /app/node_modules/
      - /app/apps/frontend/.next
    restart: on-failure

networks:
  turbo-network:
    driver: bridge